# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Currier < Formula
  desc "Vim-modal TUI API client for developers and AI agents"
  homepage "https://github.com/artpar/currier"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artpar/currier/releases/download/v0.1.11/currier_darwin_amd64.tar.gz"
      sha256 "df4352e99d16df0667bd1e85494aaa0a9b5da3733710e4f304889b4109d8e553"

      def install
        bin.install "currier"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artpar/currier/releases/download/v0.1.11/currier_darwin_arm64.tar.gz"
      sha256 "26ca4a5933629bf6029ffd03039b356c32b1c9154b192ec1586cd37ef4869ca0"

      def install
        bin.install "currier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/currier/releases/download/v0.1.11/currier_linux_amd64.tar.gz"
      sha256 "2ecfd7ef351367302bdb9575a71b88157a9d523bbd3538930c9b5148d832c498"
      def install
        bin.install "currier"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/currier/releases/download/v0.1.11/currier_linux_arm64.tar.gz"
      sha256 "946a8d422c1a4e225ccead4d0c0ce44a2fd76ede958602b7a775a7ee0e1856a3"
      def install
        bin.install "currier"
      end
    end
  end

  test do
    system "#{bin}/currier", "--version"
  end
end
