# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GogentReleases < Formula
  desc "AI coding assistant CLI powered by LLMs"
  homepage "https://github.com/artpar/gogent-releases"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artpar/gogent-releases/releases/download/v0.1.0/gogent-releases_0.1.0_darwin_amd64.tar.gz"
      sha256 "3ec8ea3a52aa42073e4823c528327251ff9104669cfbfcbe590b68b98763624e"

      def install
        bin.install "gogent"
        bash_completion.install "completions/gogent.bash" => "gogent"
        zsh_completion.install "completions/gogent.zsh" => "_gogent"
        fish_completion.install "completions/gogent.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artpar/gogent-releases/releases/download/v0.1.0/gogent-releases_0.1.0_darwin_arm64.tar.gz"
      sha256 "a9898d907f488ef50edf42102e4939987792b10798604a16a5383ed789fd8d2c"

      def install
        bin.install "gogent"
        bash_completion.install "completions/gogent.bash" => "gogent"
        zsh_completion.install "completions/gogent.zsh" => "_gogent"
        fish_completion.install "completions/gogent.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/gogent-releases/releases/download/v0.1.0/gogent-releases_0.1.0_linux_amd64.tar.gz"
      sha256 "1eb7d0674832d5e8251fb6fa3130fe021a6e010ab30d97429529d4b48a6f5184"
      def install
        bin.install "gogent"
        bash_completion.install "completions/gogent.bash" => "gogent"
        zsh_completion.install "completions/gogent.zsh" => "_gogent"
        fish_completion.install "completions/gogent.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/gogent-releases/releases/download/v0.1.0/gogent-releases_0.1.0_linux_arm64.tar.gz"
      sha256 "c38784c2f2e2f04065c92f3d2a83e1b6d49aad90f7d803f6a2500e0f66f73409"
      def install
        bin.install "gogent"
        bash_completion.install "completions/gogent.bash" => "gogent"
        zsh_completion.install "completions/gogent.zsh" => "_gogent"
        fish_completion.install "completions/gogent.fish"
      end
    end
  end

  test do
    system "#{bin}/gogent", "version"
  end
end
