# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pragma < Formula
  desc "AI coding assistant CLI powered by LLMs"
  homepage "https://github.com/artpar/pragma-releases"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_darwin_amd64.tar.gz"
      sha256 "b85fc3fbde1cdd82df27ec0f33d2738b845891ab690b358c1f02ee17f4c83874"

      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_darwin_arm64.tar.gz"
      sha256 "fd8451adeb1cbe5deb0ddbf62caee0eb72950e47eb341384be97d473da553002"

      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_linux_amd64.tar.gz"
      sha256 "400680a6dc9b18e809137422c8af7ec2cd15f1b0dfbb52bae6a84b35e6690882"
      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_linux_arm64.tar.gz"
      sha256 "377c3a886ade48f77130f635b6436e2472989026cd2a3dcdaa4f47f0b7521249"
      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  test do
    system "#{bin}/pragma", "version"
  end
end
