# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PragmaReleases < Formula
  desc "AI coding assistant CLI powered by LLMs"
  homepage "https://github.com/artpar/pragma-releases"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_darwin_amd64.tar.gz"
      sha256 "5f9d594c38e54f463479e458c93aa0b070fe847d0e032ae9ddfeecf7a47362f2"

      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_darwin_arm64.tar.gz"
      sha256 "b574cd46ff7554cdd948b5c6d43d8ead84c112b1f8a8452ef0db2f4a20e6f58e"

      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_linux_amd64.tar.gz"
      sha256 "51070335abb68fce626b18aa854955a6732de89252b59c7854b9db1189bbdf26"
      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_linux_arm64.tar.gz"
      sha256 "546f6a3e25b19e9bd72cbf0abe4c44231371b521ffeffb34758b2080af8459d3"
      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  test do
    system "#{bin}/pragma", "version"
  end
end
