# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pragma < Formula
  desc "AI coding assistant CLI powered by LLMs"
  homepage "https://github.com/artpar/pragma-releases"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_darwin_amd64.tar.gz"
      sha256 "e743a7155edc08c399ed3a7bc03a33780370c1ec2ad68849c2b760ddbfb282ed"

      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_darwin_arm64.tar.gz"
      sha256 "3f438c33884c8776abd7b634b9cd024c3f9042565c65303bd2f885bea8d6a793"

      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_linux_amd64.tar.gz"
      sha256 "04846b3915e40bc7d4126faad321c43b29f592740c5c6f228055f60922f4264a"
      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.0/pragma-releases_0.1.0_linux_arm64.tar.gz"
      sha256 "b973dd2237bd3d02fb70ab6a1d723d29feedc78bd0337d89f140d42f7caa746c"
      def install
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  test do
    system "#{bin}/pragma", "version"
  end
end
