# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pragma < Formula
  desc "AI coding assistant CLI powered by LLMs"
  homepage "https://github.com/artpar/pragma-releases"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.1/pragma-releases_0.1.1_darwin_amd64.tar.gz"
      sha256 "d24b13149ec48029d6948275bdd9aa4c2dbdf3213ce5f076aa23292917d26ccd"

      define_method(:install) do
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.1/pragma-releases_0.1.1_darwin_arm64.tar.gz"
      sha256 "b81e417cfb7d802871bfd6dab918a30b42e13fff79a054a862b51dcf1b7bb2a9"

      define_method(:install) do
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.1/pragma-releases_0.1.1_linux_amd64.tar.gz"
      sha256 "1d386a9465002536af08f431d466e8f48aeb1e1a85f060b4d62d5b0a4ad94fc3"
      define_method(:install) do
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artpar/pragma-releases/releases/download/v0.1.1/pragma-releases_0.1.1_linux_arm64.tar.gz"
      sha256 "6f1aec7126056b1560471a4fde3246d32f281b92f9bd9c6e61e60864a8a0b2db"
      define_method(:install) do
        bin.install "pragma"
        bash_completion.install "completions/pragma.bash" => "pragma"
        zsh_completion.install "completions/pragma.zsh" => "_pragma"
        fish_completion.install "completions/pragma.fish"
      end
    end
  end

  test do
    system "#{bin}/pragma", "version"
  end
end
